import { ThreatEntry, WeatherSignal, GraphNode, GraphEdge } from "./types";

export const threats: ThreatEntry[] = [
  {
    id: "pay-proof-001",
    title: "Fake UPI payment proof",
    surface: "payment trust",
    status: "active",
    summary: "Doctored screenshots claiming successful payment before goods are handed over.",
    firstSeen: "2025-11-03",
    lastSeen: "2026-03-09",
    languages: ["English", "Hindi", "Marathi"],
    redFlags: ["cropped bank UI", "no reference match", "urgency to release goods"],
    actions: ["do not hand over goods", "verify in bank app", "warn staff"]
  },
  {
    id: "qr-002",
    title: "QR pull-payment trap",
    surface: "payment trust",
    status: "rising",
    summary: "Victim is told scanning a QR will receive money, but it actually authorizes payment.",
    firstSeen: "2025-08-10",
    lastSeen: "2026-03-09",
    languages: ["English", "Hindi", "Gujarati", "Tamil"],
    redFlags: ["receive-money claim", "customer support impersonation", "scan pressure"],
    actions: ["never scan to receive", "verify caller", "share family alert"]
  },
  {
    id: "courier-003",
    title: "Courier redelivery scam",
    surface: "link trust",
    status: "active",
    summary: "Delivery-themed phishing with payment/retry links and fake support pages.",
    firstSeen: "2025-06-14",
    lastSeen: "2026-03-09",
    languages: ["English", "Hindi"],
    redFlags: ["tiny fee request", "shortened links", "delivery urgency"],
    actions: ["do not click", "open official app directly", "report message"]
  },
  {
    id: "voice-004",
    title: "Relative-in-distress voice deepfake",
    surface: "identity trust",
    status: "watch",
    summary: "Synthetic or imitated voice calls asking for urgent transfers.",
    firstSeen: "2025-12-01",
    lastSeen: "2026-03-07",
    languages: ["English", "Hindi"],
    redFlags: ["panic tone", "urgent transfer", "new number", "do not tell anyone"],
    actions: ["call known number back", "do not transfer", "verify with family"]
  },
  {
    id: "kyc-005",
    title: "KYC update fraud",
    surface: "identity trust",
    status: "active",
    summary: "SMS/WhatsApp claiming bank KYC is expiring. Links to fake portal that harvests credentials.",
    firstSeen: "2024-09-15",
    lastSeen: "2026-03-09",
    languages: ["Hindi", "English", "Bengali", "Telugu"],
    redFlags: ["urgency ('24 hours')", "link to non-.gov.in domain", "asks for OTP/Aadhaar/PAN"],
    actions: ["banks never ask for KYC via SMS links", "visit bank branch directly", "call 1930 if data shared"]
  },
  {
    id: "arrest-006",
    title: "Digital arrest scam",
    surface: "identity trust",
    status: "active",
    summary: "Video call from 'CBI/police/customs' claiming warrant exists. Increasingly uses AI deepfake video overlays and voice cloning to create fake courtrooms. Demands money to 'clear charges'.",
    firstSeen: "2025-06-20",
    lastSeen: "2026-03-09",
    languages: ["Hindi", "English"],
    redFlags: ["video call from 'officer'", "demand for immediate payment", "threat of arrest", "deepfake video of police station or courtroom", "AI-cloned voice of known person"],
    actions: ["police never call to demand money", "hang up immediately", "report at cybercrime.gov.in"]
  },
  {
    id: "task-007",
    title: "Task-based earning scam",
    surface: "payment trust",
    status: "active",
    summary: "Telegram/WhatsApp group offering money for simple tasks. Initial payouts are real, then large 'investment' is demanded.",
    firstSeen: "2025-03-01",
    lastSeen: "2026-03-09",
    languages: ["Hindi", "English", "Tamil", "Telugu"],
    redFlags: ["too good to be true returns", "'investment' after initial tasks", "crypto/UPI deposits required"],
    actions: ["no legitimate job requires you to invest", "stop immediately", "save screenshots as evidence"]
  },
  {
    id: "job-009",
    title: "Fake job interview fee scam",
    surface: "payment trust",
    status: "rising",
    summary: "Fraudulent recruiter demands payment for 'registration', 'training materials', 'background check', or 'interview slot booking'. Often impersonates TCS, Infosys, Wipro, or government PSUs.",
    firstSeen: "2024-06-01",
    lastSeen: "2026-03-09",
    languages: ["Hindi", "English", "Telugu", "Tamil", "Kannada"],
    redFlags: ["payment demanded before interview", "offer letter before interview", "WhatsApp/Telegram-only communication", "generic company email (gmail/yahoo)", "unrealistic salary for entry-level"],
    actions: ["no legitimate employer charges for interviews", "verify on official company careers page", "check recruiter on LinkedIn", "report at cybercrime.gov.in"]
  },
  {
    id: "lottery-008",
    title: "KBC / lottery scam",
    surface: "payment trust",
    status: "active",
    summary: "WhatsApp message claiming lottery win. Demands 'processing fee' or 'tax' payment.",
    firstSeen: "2023-01-10",
    lastSeen: "2026-03-09",
    languages: ["Hindi", "English", "Bengali"],
    redFlags: ["you didn't enter any lottery", "processing fee demanded", "WhatsApp forward chain"],
    actions: ["KBC never contacts winners via WhatsApp", "never pay to claim a prize", "block and report"]
  },
  {
    id: "sim-swap-010",
    title: "SIM swap fraud",
    surface: "identity trust",
    status: "active",
    summary: "Scammer gets a duplicate SIM issued in your name, intercepts OTPs, and drains bank accounts.",
    firstSeen: "2024-01-15",
    lastSeen: "2026-03-15",
    languages: ["Hindi", "English"],
    redFlags: ["sudden loss of mobile signal", "unexpected 'SIM upgrade' calls", "bank OTPs you didn't request"],
    actions: ["call your operator immediately if signal drops", "set SIM lock PIN", "enable app-based 2FA instead of SMS"]
  },
  {
    id: "aadhaar-otp-011",
    title: "Aadhaar OTP fraud",
    surface: "identity trust",
    status: "active",
    summary: "Caller claims to be from UIDAI or bank, asks for Aadhaar number and OTP to 'verify' or 'link' your account.",
    firstSeen: "2024-03-01",
    lastSeen: "2026-03-10",
    languages: ["Hindi", "English", "Telugu", "Tamil"],
    redFlags: ["UIDAI never calls citizens", "asks for Aadhaar OTP over phone", "threatens account closure"],
    actions: ["UIDAI never asks for OTP over phone", "lock Aadhaar biometrics at myaadhaar.uidai.gov.in", "report to 1930"]
  },
  {
    id: "crypto-pig-012",
    title: "Crypto investment / pig butchering scam",
    surface: "payment trust",
    status: "rising",
    summary: "Builds trust over weeks via dating apps or WhatsApp, then lures into fake crypto trading platform. Initial profits are fake.",
    firstSeen: "2024-06-01",
    lastSeen: "2026-03-12",
    languages: ["English", "Hindi"],
    redFlags: ["stranger builds romantic/trust relationship first", "custom trading app or website", "can't withdraw after initial profits", "asks to invest more to unlock funds"],
    actions: ["never invest on platforms recommended by online strangers", "verify exchange on SEBI/RBI lists", "screenshot everything and report"]
  },
  {
    id: "matrimonial-013",
    title: "Matrimonial / dating scam",
    surface: "identity trust",
    status: "active",
    summary: "Fake profiles on matrimonial sites. After building trust, demands money for visa, medical emergency, or travel.",
    firstSeen: "2023-06-01",
    lastSeen: "2026-03-09",
    languages: ["English", "Hindi", "Tamil", "Bengali"],
    redFlags: ["never meets in person", "always has excuses", "asks for money before meeting", "profile photos look too polished"],
    actions: ["video call before sending any money", "reverse image search profile photos", "never send money to someone you haven't met"]
  },
  {
    id: "electricity-014",
    title: "Electricity bill disconnection scam",
    surface: "payment trust",
    status: "active",
    summary: "SMS claiming electricity will be disconnected today unless you pay immediately via a link or call a number.",
    firstSeen: "2024-08-01",
    lastSeen: "2026-03-10",
    languages: ["Hindi", "English", "Marathi", "Bengali"],
    redFlags: ["threats of same-day disconnection", "payment via UPI to personal ID", "unknown sender number"],
    actions: ["check your bill on the official DISCOM app", "never pay via links in SMS", "call your DISCOM's official number"]
  },
  {
    id: "insurance-015",
    title: "Fake insurance / policy scam",
    surface: "payment trust",
    status: "active",
    summary: "Call claiming your old policy has matured or you're owed a bonus. Demands processing fee or GST payment to release funds.",
    firstSeen: "2024-01-10",
    lastSeen: "2026-03-08",
    languages: ["Hindi", "English"],
    redFlags: ["claims about policies you don't remember", "processing fee to release money", "pressure to pay immediately"],
    actions: ["verify with IRDAI or your insurance company directly", "never pay fees to receive payouts", "report to 1930"]
  },
  {
    id: "rbi-sebi-016",
    title: "Fake RBI / SEBI notice",
    surface: "identity trust",
    status: "watch",
    summary: "WhatsApp or email with fake letterhead from RBI/SEBI claiming your account is under investigation or needs verification.",
    firstSeen: "2025-01-15",
    lastSeen: "2026-03-05",
    languages: ["English", "Hindi"],
    redFlags: ["RBI/SEBI logo on WhatsApp message", "asks for bank details or KYC", "threatens legal action"],
    actions: ["RBI/SEBI never contact individuals via WhatsApp", "verify on rbi.org.in or sebi.gov.in", "report the number"]
  },
  {
    id: "telegram-invest-017",
    title: "Telegram trading / investment group scam",
    surface: "payment trust",
    status: "rising",
    summary: "Added to Telegram groups showing fake trading screenshots and profits. Asked to invest via UPI. Initial returns are paid from new victims' money.",
    firstSeen: "2025-02-01",
    lastSeen: "2026-03-12",
    languages: ["Hindi", "English", "Gujarati"],
    redFlags: ["added to group without consent", "screenshots of huge profits", "admin pressures quick investment", "uses words like 'guaranteed' or 'risk-free'"],
    actions: ["leave the group immediately", "no legitimate investment is risk-free", "report group to Telegram and 1930"]
  },
  {
    id: "whatsapp-gold-018",
    title: "WhatsApp Gold / premium version scam",
    surface: "link trust",
    status: "cooling",
    summary: "Message claiming exclusive 'WhatsApp Gold' or 'Premium' version with extra features. Link installs malware.",
    firstSeen: "2022-01-01",
    lastSeen: "2026-02-20",
    languages: ["Hindi", "English"],
    redFlags: ["claims about secret WhatsApp version", "download link to APK", "forwarded many times"],
    actions: ["WhatsApp has no 'Gold' version", "only install from Play Store / App Store", "don't click APK download links"]
  },
  {
    id: "delivery-otp-019",
    title: "Fake delivery OTP scam",
    surface: "identity trust",
    status: "active",
    summary: "Caller claims to be delivery agent and asks you to share an OTP 'to confirm delivery'. That OTP is actually for a payment or account change.",
    firstSeen: "2025-01-01",
    lastSeen: "2026-03-11",
    languages: ["Hindi", "English", "Kannada"],
    redFlags: ["delivery agent asking for OTP", "OTP from bank or UPI app, not delivery service", "pressure to share quickly"],
    actions: ["delivery never requires OTP sharing", "check your bank app for any pending transaction", "report to 1930"]
  },
  {
    id: "rental-020",
    title: "Rental / housing deposit scam",
    surface: "payment trust",
    status: "active",
    summary: "Fake rental listings on OLX, 99acres, or NoBroker. Demands advance deposit before showing property. Property doesn't exist or belongs to someone else.",
    firstSeen: "2024-04-01",
    lastSeen: "2026-03-10",
    languages: ["Hindi", "English", "Kannada", "Tamil"],
    redFlags: ["rent far below market rate", "demands advance before visit", "photos stolen from other listings", "owner claims to be 'out of town'"],
    actions: ["always visit property in person first", "verify ownership documents", "never pay before visiting", "use registered brokers"]
  },
  {
    id: "loan-app-021",
    title: "Predatory loan app harassment",
    surface: "identity trust",
    status: "rising",
    summary: "Unofficial loan apps that access your contacts, then harass you and your contacts with abusive messages and morphed photos if you miss payments.",
    firstSeen: "2024-01-01",
    lastSeen: "2026-03-12",
    languages: ["Hindi", "English", "Telugu", "Tamil", "Kannada"],
    redFlags: ["unknown app asking for contact access", "extremely easy approval", "very high interest rates hidden in fine print", "threats and contact harassment"],
    actions: ["only use RBI-registered lenders", "check RBI's list at sachet.rbi.org.in", "report harassment to cybercrime.gov.in", "do not delete evidence"]
  },
  {
    id: "customs-parcel-022",
    title: "Customs / parcel seizure scam",
    surface: "identity trust",
    status: "active",
    summary: "Call claiming customs has seized a parcel in your name containing drugs or illegal goods. Demands money to 'clear' it or threatens arrest.",
    firstSeen: "2025-03-01",
    lastSeen: "2026-03-09",
    languages: ["Hindi", "English"],
    redFlags: ["call from 'customs officer'", "claims drugs found in your parcel", "demands immediate payment to avoid arrest", "transfers call to 'police'"],
    actions: ["customs never calls demanding money", "hang up immediately", "real investigations happen in writing", "report to 1930"]
  },
  {
    id: "fake-app-023",
    title: "Fake banking / government app",
    surface: "link trust",
    status: "active",
    summary: "APK sent via WhatsApp or SMS claiming to be a bank app, income tax app, or government utility. Installs spyware that steals credentials.",
    firstSeen: "2024-06-01",
    lastSeen: "2026-03-10",
    languages: ["Hindi", "English", "Bengali"],
    redFlags: ["APK file shared via WhatsApp", "asks to enable 'unknown sources'", "looks like official app but from wrong source"],
    actions: ["only install apps from Play Store / App Store", "never enable 'unknown sources' for banking apps", "verify app developer name matches official bank"]
  },
  {
    id: "screen-share-024",
    title: "Screen share / remote access scam",
    surface: "identity trust",
    status: "rising",
    summary: "Caller asks you to install AnyDesk, TeamViewer, or QuickSupport to 'fix' a problem. Then watches you enter passwords and initiates transfers.",
    firstSeen: "2024-09-01",
    lastSeen: "2026-03-12",
    languages: ["Hindi", "English"],
    redFlags: ["asks to install remote access app", "claims to be bank tech support", "watches your screen while you do banking", "asks to 'show' your balance"],
    actions: ["no bank asks you to install remote access apps", "uninstall AnyDesk/TeamViewer if installed by a stranger", "report to 1930"]
  },
  {
    id: "collect-request-025",
    title: "UPI collect request scam",
    surface: "payment trust",
    status: "active",
    summary: "You receive a UPI collect request claiming to be a refund or cashback. Approving it sends money FROM your account, not to it.",
    firstSeen: "2024-01-01",
    lastSeen: "2026-03-09",
    languages: ["Hindi", "English", "Tamil", "Telugu", "Marathi"],
    redFlags: ["unexpected collect request", "claims it's a refund", "unknown VPA/UPI ID", "amount doesn't match any transaction"],
    actions: ["receiving money never requires approving a collect request", "decline unknown collect requests", "verify with the sender separately"]
  },
  {
    id: "trading-tips-026",
    title: "Stock trading tips scam",
    surface: "payment trust",
    status: "active",
    summary: "WhatsApp or Telegram messages offering guaranteed stock tips for a fee. Often impersonates SEBI-registered analysts.",
    firstSeen: "2024-06-01",
    lastSeen: "2026-03-10",
    languages: ["Hindi", "English", "Gujarati"],
    redFlags: ["guaranteed returns on stock picks", "screenshots of past 'wins'", "fee demanded upfront", "impersonates known analysts"],
    actions: ["verify advisor registration on SEBI website", "no one can guarantee stock returns", "report to SEBI at scores.gov.in"]
  },
  {
    id: "charity-027",
    title: "Fake charity / disaster relief scam",
    surface: "payment trust",
    status: "watch",
    summary: "Fake donation drives after natural disasters or festivals. Money goes to scammers, not victims.",
    firstSeen: "2024-01-01",
    lastSeen: "2026-03-01",
    languages: ["Hindi", "English", "Bengali"],
    redFlags: ["unknown charity name", "only accepts UPI to personal account", "emotional manipulation", "no website or registration"],
    actions: ["donate only through verified platforms", "check NGO registration at ngodarpan.gov.in", "don't donate via personal UPI IDs"]
  },
  {
    id: "olx-prepay-028",
    title: "OLX / marketplace prepayment scam",
    surface: "payment trust",
    status: "active",
    summary: "Seller on OLX or Facebook Marketplace demands advance payment, then blocks you after receiving money.",
    firstSeen: "2023-06-01",
    lastSeen: "2026-03-10",
    languages: ["Hindi", "English"],
    redFlags: ["price too good to be true", "demands full advance", "refuses to meet in person", "newly created profile"],
    actions: ["always meet in person for high-value items", "use platform's secure payment if available", "never send full payment in advance"]
  },
  {
    id: "pan-update-029",
    title: "PAN card update / link scam",
    surface: "identity trust",
    status: "active",
    summary: "SMS claiming PAN needs to be linked or updated urgently, with a phishing link that steals personal and bank details.",
    firstSeen: "2025-01-01",
    lastSeen: "2026-03-10",
    languages: ["Hindi", "English"],
    redFlags: ["urgency about PAN linking deadline", "link to non-gov.in domain", "asks for bank account details along with PAN"],
    actions: ["PAN updates only through incometax.gov.in", "never click SMS links for PAN", "visit income tax office if needed"]
  },
  {
    id: "deepfake-celeb-030",
    title: "Deepfake celebrity endorsement scam",
    surface: "identity trust",
    status: "rising",
    summary: "AI-generated videos of celebrities endorsing investment schemes, health products, or apps. Used in social media ads.",
    firstSeen: "2025-06-01",
    lastSeen: "2026-03-15",
    languages: ["Hindi", "English"],
    redFlags: ["celebrity endorsing something unusual", "unnatural lip sync", "ad leads to unknown website", "too-good-to-be-true claims"],
    actions: ["verify on celebrity's official social accounts", "screenshot the ad for evidence", "report to platform and cybercrime.gov.in"]
  },
  {
    id: "sextortion-031",
    title: "Sextortion / morphed photo blackmail",
    surface: "identity trust",
    status: "rising",
    summary: "Scammer befriends victim on social media or dating app, obtains or morphs intimate photos, then demands money threatening to share with contacts. 19% of all cybercrime cases in India.",
    firstSeen: "2024-01-01",
    lastSeen: "2026-03-15",
    languages: ["Hindi", "English", "Bengali", "Tamil"],
    redFlags: ["stranger pushes for intimate photos early", "video call freezes conveniently", "sudden demand for money", "threats to share with your contact list"],
    actions: ["do not pay — payment leads to more demands", "screenshot all threats as evidence", "report to cybercrime.gov.in immediately", "block the sender", "inform trusted family member"]
  },
  {
    id: "invest-pig-032",
    title: "Investment / pig butchering scam",
    surface: "payment trust",
    status: "rising",
    summary: "Contacted via WhatsApp/Telegram/Instagram with stock tips or crypto opportunities. Victims are groomed with small real returns on fake trading apps, then lose everything when withdrawals are blocked. 75% of all cybercrime losses in India.",
    firstSeen: "2024-06-01",
    lastSeen: "2026-03-15",
    languages: ["Hindi", "English", "Gujarati", "Tamil"],
    redFlags: ["unsolicited contact with investment advice", "added to WhatsApp/Telegram groups without consent", "fake trading app not on Play Store", "guaranteed returns", "cannot withdraw after initial profits"],
    actions: ["never invest on platforms recommended by strangers", "verify on SEBI/RBI registered lists", "no legitimate investment guarantees returns", "screenshot everything", "report to 1930"]
  }
];

export const weather: WeatherSignal[] = [
  { id: "w1", label: "UPI payment fraud", pressure: 86, delta: "high", tone: "red" },
  { id: "w2", label: "Courier phishing", pressure: 62, delta: "moderate", tone: "amber" },
  { id: "w3", label: "Bank impersonation", pressure: 73, delta: "high", tone: "red" },
  { id: "w4", label: "QR traps", pressure: 58, delta: "moderate", tone: "amber" },
  { id: "w5", label: "Fake news / media panic", pressure: 41, delta: "low", tone: "violet" },
  { id: "w6", label: "Digital arrest", pressure: 82, delta: "high", tone: "amber" },
  { id: "w7", label: "KYC update fraud", pressure: 68, delta: "high", tone: "red" },
  { id: "w8", label: "Voice deepfake", pressure: 41, delta: "rising", tone: "amber" },
  { id: "w9", label: "Task / investment scam", pressure: 94, delta: "critical", tone: "red" },
  { id: "w10", label: "Fake job / interview fee", pressure: 64, delta: "moderate", tone: "amber" }
];

export const graphNodes: GraphNode[] = [
  { data: { id: "chetana", label: "Chetana", kind: "core", score: 1 } },
  { data: { id: "campaign-a", label: "UPI Scam Cluster", kind: "campaign", score: 0.92 } },
  { data: { id: "phone-a", label: "+91 98765 43210", kind: "phone", score: 0.81 } },
  { data: { id: "url-a", label: "pay-verify-now[.]xyz", kind: "url", score: 0.88 } },
  { data: { id: "merchant", label: "Merchant Mode", kind: "surface", score: 0.7 } },
  { data: { id: "family", label: "Family Shield", kind: "surface", score: 0.74 } },
  { data: { id: "nexus", label: "Chetana Nexus", kind: "enterprise", score: 0.9 } },
  { data: { id: "weather", label: "Scam Weather", kind: "intel", score: 0.76 } },
  { data: { id: "campaign-b", label: "KYC Fraud Ring", kind: "campaign", score: 0.85 } },
  { data: { id: "campaign-c", label: "Digital Arrest", kind: "campaign", score: 0.78 } },
  { data: { id: "url-b", label: "sbi-kyc-update[.]top", kind: "url", score: 0.91 } },
  { data: { id: "phone-b", label: "+91 14012 XXXXX", kind: "phone", score: 0.72 } },
  { data: { id: "atlas", label: "Scam Atlas", kind: "surface", score: 0.81 } },
  { data: { id: "campaign-d", label: "Fake Job Ring", kind: "campaign", score: 0.74 } }
];

export const graphEdges: GraphEdge[] = [
  { data: { id: "e1", source: "chetana", target: "campaign-a", label: "tracks", weight: 0.9 } },
  { data: { id: "e2", source: "campaign-a", target: "phone-a", label: "uses", weight: 0.7 } },
  { data: { id: "e3", source: "campaign-a", target: "url-a", label: "hosts", weight: 0.84 } },
  { data: { id: "e4", source: "chetana", target: "merchant", label: "protects", weight: 0.6 } },
  { data: { id: "e5", source: "chetana", target: "family", label: "alerts", weight: 0.75 } },
  { data: { id: "e6", source: "chetana", target: "nexus", label: "powers", weight: 0.87 } },
  { data: { id: "e7", source: "chetana", target: "weather", label: "publishes", weight: 0.69 } },
  { data: { id: "e8", source: "chetana", target: "campaign-b", label: "tracks", weight: 0.85 } },
  { data: { id: "e9", source: "chetana", target: "campaign-c", label: "tracks", weight: 0.78 } },
  { data: { id: "e10", source: "campaign-b", target: "url-b", label: "hosts", weight: 0.91 } },
  { data: { id: "e11", source: "campaign-c", target: "phone-b", label: "uses", weight: 0.72 } },
  { data: { id: "e12", source: "chetana", target: "atlas", label: "curates", weight: 0.81 } },
  { data: { id: "e13", source: "campaign-a", target: "campaign-b", label: "overlaps", weight: 0.45 } },
  { data: { id: "e14", source: "chetana", target: "campaign-d", label: "tracks", weight: 0.74 } }
];

export const tuiLines = [
  "[mirror] booting trust shell...",
  "[weather] UPI scam pressure elevated",
  "[atlas] threat library refreshed: 4 visible campaigns",
  "[witness] payment-proof lane enabled",
  "[nexus] analyst replay preview ready",
  "[family] share-safe warning cards compiled",
  "[merchant] fake payment screenshot advisory updated",
  "[mirrorgraph] living visual synced"
];
